#!/bin/bash

c=0
while [ 1 = 1 ]; do
 for i in `seq 0 575`; do
  let j=$((i<<6))+c
  
  k=`printf "\x%02X" $((j>>8))`
  l=`printf "\x%02X" $((j&255))`
  
  #Multi-line comment!!!
  : '
  printf '%x\n' $j
  echo $k
  echo $l
  echo $k$l
  '
 
  echo -e "$k$l" | nc 192.168.4.69 5045 -q0
 
  sleep 2
 done
 
 let c=c+1
 let c=$((c%3))
done
